### ISSUE TITLE
Problema con AllowDiskTrue

### ISSUE THREAD

**Issue by CCM-29** [ernestojr/search-service-mongoose#1]
Se encontro el siguiente bug en el proyecto:

Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation,

por lo que revisando el codigo del proyecto se encontro que en este hay un problema en la linea 113 del codigo de index.js

y para resolverlo se agrego el siguiente valor 
`return model.aggregate(query).allowDiskUse(true);`

**Comment by ernestojr** [comment]
Hola, Gracias por reportarlo, podrías por favor indicar la forma en la que pueda reproducir el problema. Quedo atento a tu respuesta.

**Comment by CCM-29** [comment]
El problema sucede cuando se quiere hacer un sort a una cantidad de registros muy grande (1 millon), es un erro conocido

Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation

Saludos

**Comment by ernestojr** [comment]
Vale, dejaré por acá la solución de este issue.

**Comment by ernestojr** [comment]
Se acaba de resolver este issue en [bcbda21](https://github.com/ernestojr/search-service-mongoose/commit/bcbda21b0d4322efe3a9718b70912a53f8aec5a2). Ahora dentro de las opciones de busqueda, se agregó la opción `allowDiskUse`.
